### ISSUE TITLE
Remove whitespace-trimming code 

### ISSUE THREAD

**Issue by kylebarron** [nikitakit/hydrogen-python#12]
The suggestion I had last night didn't make it into that PR.

What would you think about having a simple `code.replace(/^\n|\n$/g, '')` to fix 
<img width="480" alt="image" src="https://user-images.githubusercontent.com/15164633/43436698-8c05e228-9453-11e8-8c0e-e219b45f6e02.png">

**Comment by nikitakit** [comment]
Oh, so the issue here that the first line doesn't have any indentation, which trips up IPython's indentation detection?

In that case, there does need to be an update that's timed with the new hydrogen version that removes the trim. Hopefully IPython doesn't choke if there are non-indented empty lines in the middle of the code, or there will be even more work to be done...

**Comment by kylebarron** [comment]
IPython is fine if there are non-indented lines in the middle. But when the first line has no indentation, that causes an error.

**Comment by nikitakit** [comment]
Changes are currently staged on the master branch, to be released soon (hopefully I can test some more before releasing)
